--------------------------------------------------------
--  File created - Tuesday-April-22-2025   
--------------------------------------------------------
REM INSERTING into SYSTEM.CUSTOMER_PROFILES
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER_PROFILES (ID,NAME,EMAIL) values (1,'John Smith','john.smith@example.com');
Insert into SYSTEM.CUSTOMER_PROFILES (ID,NAME,EMAIL) values (2,'Maria Garcia','maria.garcia@example.com');
Insert into SYSTEM.CUSTOMER_PROFILES (ID,NAME,EMAIL) values (3,'Ahmed Khan','ahmed.khan@example.com');
REM INSERTING into SYSTEM.PRODUCTS
SET DEFINE OFF;
Insert into SYSTEM.PRODUCTS (ID,NAME,PRICE,DESCRIPTION) values (1,'Premium Laptop',1299.99,'High-performance laptop for professionals');
Insert into SYSTEM.PRODUCTS (ID,NAME,PRICE,DESCRIPTION) values (2,'Ergonomic Office Chair',249.99,'Comfortable chair with lumbar support');
Insert into SYSTEM.PRODUCTS (ID,NAME,PRICE,DESCRIPTION) values (3,'Smart Home Hub',179.5,'<b>Voice-controlled</b> smart home <i>central hub</i> with <span style="color:blue">wireless connectivity</span>');
REM INSERTING into SYSTEM.ANALYTICS_DATA
SET DEFINE OFF;
Insert into SYSTEM.ANALYTICS_DATA (ID,EVENT_TYPE,TIMESTAMP,USER_ID) values (1,'page_view',to_timestamp('20 APR 2025 08.15.32.452000000','DD MON RRRR HH24.MI.SSXFF'),1001);
Insert into SYSTEM.ANALYTICS_DATA (ID,EVENT_TYPE,TIMESTAMP,USER_ID) values (2,'purchase',to_timestamp('20 APR 2025 10.38.14.129000000','DD MON RRRR HH24.MI.SSXFF'),1042);
Insert into SYSTEM.ANALYTICS_DATA (ID,EVENT_TYPE,TIMESTAMP,USER_ID) values (3,'search',to_timestamp('21 APR 2025 15.22.40.781000000','DD MON RRRR HH24.MI.SSXFF'),1098);
--------------------------------------------------------
--  DDL for Index SYS_C008435
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008435" ON "SYSTEM"."CUSTOMER_PROFILES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_CUSTOMER_EMAIL
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_CUSTOMER_EMAIL" ON "SYSTEM"."CUSTOMER_PROFILES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008434
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008434" ON "SYSTEM"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_PRODUCTS_NAME
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_PRODUCTS_NAME" ON "SYSTEM"."PRODUCTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008436
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008436" ON "SYSTEM"."ANALYTICS_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_ANALYTICS_EVENT_TYPE
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_ANALYTICS_EVENT_TYPE" ON "SYSTEM"."ANALYTICS_DATA" ("EVENT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_PROFILES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_PROFILES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMER_PROFILES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PRODUCTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_METADATA_JSON" CHECK (METADATA IS JSON) ENABLE;
--------------------------------------------------------
--  Constraints for Table ANALYTICS_DATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANALYTICS_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ANALYTICS_DATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
